app/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('pages.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"
urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
]

pages/models.py
from django.db import models

# Create your models here.

pages/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'pages/index.html', {

    })


def about(request):
    return render(request, 'pages/about.html', {

    })

app/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  </head>
  <body>
    <div class="wrapper pt-16 min-h-screen flex flex-col	">
      <nav class="navbar bg-gray-800 fixed w-full top-0 left-0">
        <div class="wrap h-16 flex flex-row px-4 items-center">
          <a href="{% url 'pages:index' %}" class="text-white text-lg font-bold"
            >201PROJECT</a
          >
          <div class="navbar__gnb ml-6">
            <a href="" class="text-gray-500 hover:text-gray-300 text-sm"
              >Home</a
            >
            <a href="" class="ml-4 text-gray-500 hover:text-gray-300 text-sm"
              >Peoples</a
            >
            <a href="" class="ml-4 text-gray-500 hover:text-gray-300 text-sm"
              >Projects</a
            >
          </div>

          <div class="ml-auto">
            <a href="" class="text-sm text-gray-500 hover:text-gray-300"
              >로그인/회원가입</a
            >
          </div>
        </div>
      </nav>
      <div class="sub-navbar">
        <div class="wrap flex flex-row px-4 items-center h-10 shadow-md">
          <a href="" class="mr-6 text-gray-600 hover:text-gray-900 text-sm"
            >Link</a
          >
          <a href="" class="mr-6 text-gray-600 hover:text-gray-900 text-sm">
            Link <small class="badge">12</small>
          </a>
          <a href="" class="mr-6 text-gray-600 hover:text-gray-900 text-sm">
            Link <small class="badge">12</small>
          </a>
          <a href="" class="mr-6 text-gray-600 hover:text-gray-900 text-sm">
            Link <small class="badge">12</small>
          </a>
          <a href="" class="mr-6 text-gray-600 hover:text-gray-900 text-sm">
            Link <small class="badge">12</small>
          </a>
        </div>
      </div>

      <div class="container">
        {% block content %} {% endblock content %}
      </div>

      <footer class="footer mt-auto bg-gray-200 p-8">
        <div class="footer__link">
          <a
            href="https://github.com/jimlee91/201Project"
            class="text-sm mr-4"
            target="_blank"
            >GitHub</a
          >
          <a href="{% url 'pages:about' %}" class="text-sm">About</a>
        </div>
        <div class="footer__copyright mt-4 text-sm text-gray-700 font-light">
          2020 &copy; 201PROJECT. All rights reserved.
        </div>
      </footer>
    </div>
  </body>
</html>

pages/templates/pages/about.html
{% extends 'layout.html' %}

{% block content %}
Hello! About
{% endblock content %}

pages/templates/pages/index.html
{% extends 'layout.html' %}

{% block content %}
Hello Index!
{% endblock content %}